# Generated by Django 4.2.23 on 2025-07-29 06:30

from django.db import migrations, models
import django_s3_storage.storage
import project.routedb.models


class Migration(migrations.Migration):

    dependencies = [
        ('routedb', '0026_route_routedb_rou_start_t_bdae44_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='mapdump'), upload_to=project.routedb.models.avatar_upload_path),
        ),
    ]
