version: 2
jobs:
  build:
    # to speed up Dockers builds turn on layer caching
    # which is a paid CircleCI feature
    # https://circleci.com/docs/2.0/docker-layer-caching/
    machine:
      docker_layer_caching: false
    steps:
    - checkout
    - run: mkdir -p media/drawmyroute-maps/
    - run: ./dc build
    - run: ./dc up -d
    - run: ./da migrate
    - run:
        name: Install Yarn and add react-scripts
        # https://www.cloudesire.com/how-to-upgrade-node-on-circleci-machine-executor/
        command: |
          export NVM_DIR="/opt/circleci/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm install v14 && nvm use v14 && nvm alias default v14
          node -v
          curl -o- -L https://yarnpkg.com/install.sh | bash
          cd project/frontend/
          ~/.yarn/bin/yarn add react-scripts
    - run: ./da build_frontend
    - run: timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost)" != "200" ]]; do sleep 5; done' || false
    - run:
        name: Run cypress
        # https://www.cloudesire.com/how-to-upgrade-node-on-circleci-machine-executor/
        command: |
          export NVM_DIR="/opt/circleci/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm install v14 && nvm use v14 && nvm alias default v14
          apt-get update
          apt-get install -y libgbm-dev
          node -v
          ~/.yarn/bin/yarn install
          ~/.yarn/bin/yarn cypress install
          ~/.yarn/bin/yarn cypress run
    - store_artifacts:
        path: cypress/videos
    - store_artifacts:
        path: cypress/screenshots
workflows:
  build:
    jobs:
    - build
  version: 2
