version: 2
jobs:
  build:
    # to speed up Dockers builds turn on layer caching
    # which is a paid CircleCI feature
    # https://circleci.com/docs/2.0/docker-layer-caching/
    machine:
      docker_layer_caching: false
    steps:
    - checkout
    - run: ./dc build
    - run: ./dc up -d
    - run: cd frontend
    - run: curl -o- -L https://yarnpkg.com/install.sh | bash
    - run: yarn run cypress run
workflows:
  build:
    jobs:
    - build
  version: 2