version: 2
jobs:
  build-and-test:
    # to speed up Dockers builds turn on layer caching
    # which is a paid CircleCI feature
    # https://circleci.com/docs/2.0/docker-layer-caching/
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: false
    steps:
    - checkout
    - run: mkdir -p media/drawmyroute-maps/
    - run: ./dc build
    - run: ./dc up -d
    - run: ./da migrate
    - run:
        name: Install Yarn and add react-scripts
        # https://www.cloudesire.com/how-to-upgrade-node-on-circleci-machine-executor/
        command: |
          export NVM_DIR="/opt/circleci/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm install v14 && nvm use v14 && nvm alias default v14
          node -v
          curl -o- -L https://yarnpkg.com/install.sh | bash
          cd project/frontend/
          ~/.yarn/bin/yarn add react-scripts
    - run: ./da build_frontend
    - run: timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080)" != "200" ]]; do sleep 5; done' || false
    - run:
        name: Run cypress
        # https://www.cloudesire.com/how-to-upgrade-node-on-circleci-machine-executor/
        command: |
          export NVM_DIR="/opt/circleci/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm install v14 && nvm use v14 && nvm alias default v14
          sudo apt-get update
          sudo apt-get install -y libgbm-dev
          node -v
          ~/.yarn/bin/yarn install
          ~/.yarn/bin/yarn cypress install
          ~/.yarn/bin/yarn cypress run
    - store_artifacts:
        path: cypress/videos
    - store_artifacts:
        path: cypress/screenshots

  deploy:
    machine:
        image: ubuntu-2004:202104-01
        docker_layer_caching: false
    steps:
    - run:
        name: Deploy
        command: |
          ssh root@routechoices.com 'sudo -u apps /apps/drawmyroute/bin/deploy'

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
    - build-and-test
    - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master

