version: 2
jobs:
  build:
    # to speed up Dockers builds turn on layer caching
    # which is a paid CircleCI feature
    # https://circleci.com/docs/2.0/docker-layer-caching/
    machine:
      docker_layer_caching: false
    steps:
    - checkout
    - run: ./dc build
    - run:
        name: Install Node.js 10 with build in nvm tool
        # https://www.cloudesire.com/how-to-upgrade-node-on-circleci-machine-executor/
        command: |
          export NVM_DIR="/opt/circleci/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm install v10 && nvm use v10 && nvm alias default v10
          node -v

    - run: curl -o- -L https://yarnpkg.com/install.sh | bash
    - run: cd frontend
    - run: ~/.yarn/bin/yarn install
    - run: cd ..
    - run: ./dc up -d
    - run: cd frontend
    - run: while ! curl --output /dev/null --silent --head --fail http://localhost:3000; do sleep 1 && echo -n .; done;
    - run: ~/.yarn/bin/yarn run cypress run
workflows:
  build:
    jobs:
    - build
  version: 2