version: 2.1
commands:
  setup-docker:
    steps:
      - run:
          name: Setup buildx and qemu
          command: |
            sudo apt-get update
            sudo apt-get install -y qemu-user-static
            sudo apt-get install -y binfmt-support
      - run:
          name: Check versions
          command: |
            qemu-aarch64-static --version
            update-binfmts --version
      - run:
          name: Create builder
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker buildx create --name arm-builder
            docker buildx use arm-builder
            docker buildx inspect --bootstrap

jobs:
  build-and-test:
    # to speed up Dockers builds turn on layer caching
    # which is a paid CircleCI feature
    # https://circleci.com/docs/2.0/docker-layer-caching/
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: false
    resource_class: large
    steps:
    - checkout
    - run: mkdir -p media/mapdump/
    - run: ./dc up -d
    - run: ./dc pipinstall
    - run: ./da migrate
    - run:
        name: Install Yarn and add react-scripts
        # https://www.cloudesire.com/how-to-upgrade-node-on-circleci-machine-executor/
        command: |
          export NVM_DIR="/opt/circleci/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm install v14 && nvm use v14 && nvm alias default v14
          node -v
          curl -o- -L https://yarnpkg.com/install.sh | bash
          cd project/frontend/
          ~/.yarn/bin/yarn add react-scripts@4.0.3
    - run: ./da build_frontend
    - run: ./dc restart django
    - run: timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080)" != "200" ]]; do sleep 5; done' || false
    - run:
        name: Run cypress
        # https://www.cloudesire.com/how-to-upgrade-node-on-circleci-machine-executor/
        command: |
          export NVM_DIR="/opt/circleci/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm install v14 && nvm use v14 && nvm alias default v14
          sudo apt-get update
          sudo apt-get install -y libgbm-dev
          node -v
          ~/.yarn/bin/yarn install
          ~/.yarn/bin/yarn cypress install
          ~/.yarn/bin/yarn cypress run
    - store_artifacts:
        path: cypress/videos
    - store_artifacts:
        path: cypress/screenshots

  deploy:
    machine:
        image: ubuntu-2204:current
        docker_layer_caching: false
    steps:
    - run:
        name: Deploy
        command: |
          ssh rphlo@mapdump.com 'sudo -u apps /apps/mapdump/bin/deploy'

  build-docker:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - checkout
      - setup-docker
      - run:
          name: Connect account
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - run:
          name: Build docker images
          command: |
            DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --platform linux/amd64 --push -t rphlo/mapdump-dev-server:latest -f docker/django.dockerfile .

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
    - build-and-test
    - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
  build_image:
    jobs:
      - build-docker:
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
