version: 2
jobs:
  build:
    # to speed up Dockers builds turn on layer caching
    # which is a paid CircleCI feature
    # https://circleci.com/docs/2.0/docker-layer-caching/
    machine:
      docker_layer_caching: false
    steps:
    - checkout
    - run:
        name: Install Node.js 10 with build in nvm tool
        # https://www.cloudesire.com/how-to-upgrade-node-on-circleci-machine-executor/
        command: |
          export NVM_DIR="/opt/circleci/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm install v10 && nvm use v10 && nvm alias default v10
          node -v
          curl -o- -L https://yarnpkg.com/install.sh | bash
          cd frontend
          ~/.yarn/bin/yarn install
          cd ..
    - run: ./dc build
    - run: ./dc up -d
    - run: timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3000)" != "200" ]]; do sleep 5; done' || false
    - run:
        name: Install Node.js 10 and run cypress
        # https://www.cloudesire.com/how-to-upgrade-node-on-circleci-machine-executor/
        command: |
          export NVM_DIR="/opt/circleci/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm install v10 && nvm use v10 && nvm alias default v10
          node -v
          curl -o- -L https://yarnpkg.com/install.sh | bash
          cd frontend
          ~/.yarn/bin/yarn install
          ~/.yarn/bin/yarn run cypress run
workflows:
  build:
    jobs:
    - build
  version: 2