version: '3.7'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: always
    expose:
      - "5432"
  minio:
    image: minio/minio:latest
    volumes:
      - ../media:/data
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ../:/app/
      - ../nginx:/etc/nginx/conf.d
    links:
      - minio
    depends_on:
      - django
    expose:
      - "8080"
  smtp:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
    expose:
      - "1025"
  django:
    container_name: md_django
    image: rphlo/mapdump-dev-server:latest
    stop_signal: SIGINT
    volumes:
      - ../:/app/:rw
    environment:
      DATABASE_URL: postgres://app_user:changeme@db/app_db
      VITE_API_URL: http://localhost:8080/api
      VITE_AVATAR_ROOT: http://localhost:8080/
    expose:
      - "8000"
    user: ${USERID}:${GROUPID}
    depends_on:
      - db
    links:
      - minio
      - db
      - smtp
    command: ['/venv/bin/python3', './project/manage.py', 'runserver', '0.0.0.0:8000']
